### PR TITLE
Trg 7.02 license and copyright header issue #77

### LINKED ISSUE #77: TRG 7.02 License and copyright header
Please update the Copyright timestamp when changing content:

https://github.com/eclipse-tractusx/sd-factory/blob/1e60d035e7f012a1d8cc1e0f6a5889018b760ee7/src/main/java/org/eclipse/tractusx/selfdescriptionfactory/service/converter/vrel3/LegalParticipantSDConverter.java#L1-L4

File was changed in 2023 (commit 5d9494f) but the copyright header timestamp ends 2022.

Depending on your IDE, there are Plugings available managing and keep the the copyright header up to date.

### PR DESCRIPTION
**Pull request by dvasunin**
### What:
Copyright and License Headers were updated in affected source files

### Why:
To be compliant with [Trg 7.02](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) and fixes #77

### CODE REVIEW

**Comment by dvasunin** [comment]
@amoldashwant please review

**Comment by amoldashwant** [comment]
There are some more files which are changed in 2023. We need to update the license header of those files too

**Comment by dvasunin** [comment]
> There are some more files which are changed in 2023. We need to update the license header of those files too

Done

**Comment by dvasunin** [comment]
@SebastianBezold please approve and merge

**Review by carslen — CHANGES_REQUESTED** [review]
I've expected to find a copyright header timestamp like this:

```
* Copyright (c) 2021,2023 T-Systems International GmbH
* Copyright (c) 2021,2023 Contributors to the Eclipse Foundation
```

Do not remove the start date of the copyright. The timestamp is a time span _startDate,currentDate_.

**Comment by dvasunin** [comment]
> I've expected to find a copyright header timestamp like this:
> 
> ```
> * Copyright (c) 2021,2023 T-Systems International GmbH
> * Copyright (c) 2021,2023 Contributors to the Eclipse Foundation
> ```
> 
> Do not remove the start date of the copyright. The timestamp is a time span _startDate,currentDate_.

I've noticed the first commit to these files were in 2022, so startDate shall not be earlier. I guess 2021 appeared there by mistake as part of a template

**Comment by MehranRoshandel** [comment]
@carslen, can you please help us merge this PR by today

**Review by carslen — APPROVED** [review]

**Pull request merged**
