### PR TITLE
Library upgrades

### PR DESCRIPTION
**Pull request by adkumar1**

### CODE REVIEW

**Comment by carslen** [comment]
Can you explain where in this PR libraries has changed? All I can see is bumping versions in the Chart and the Changelog. The Changelog changes are confusing me, because is 2.0.2 the appversion or related to the Chart version in this PR?

**Comment by dvasunin** [comment]
I have explained it in CHANGELOG, may be I shall give more details. Snakeyaml library has a critical security issue. I have upgraded it to the latest version (2.0). Meanwhile I have upgraded Spring Boot as well

**Comment by adkumar1** [comment]
Helm chart version: 2.0.2
appVersion: "2.0.1"

**Comment by carslen** [comment]
OK, got it. The updated libs are updated in pom.xml. Sorry for confusion, I'm not a Java guy, Ive overseen it.

But I still have questions to the CHANGELOG.md file: You mention there a release 2.0.2, which is missing in this repository right now. But when merging this PR, then there will be a released helm chart with version 2.0.2. But the CHANGELOG isn't for helm chart releases. 

I know that merging this PR will trigger a workflow which will create the image in the fork inside NG organization (although the image already exists, which is a problem too (changing hashes for the same image tag)). Did you think about release strategy for the application itself?

**Comment by adkumar1** [comment]
In CHANGELOG.md , Under section helm release 2.0.2
I have added the content, what change is made in that particular release.
This is what it suppose to be.

**Comment by adkumar1** [comment]
Actually image 2.0.1 is the latest and correct one.
Image with tag 2.0.2 was created by mistake with a typo. I cannot delete it, so it stayed there.

**Comment by carslen** [comment]
OK, got it. Shall we delete the image with tag 2.0.2 then, to avoid this kind of confusion?

But Changelog is still an issue. 

If the Changelog contains a version 
* then there has to be a GH Release with this version
* a released helm chart must be available (release upfront) to install this version
* a image with a version matching tag

This PR will release a Helm chart in version 2.0.2 which will install appVersion 2.0.1 (which also misses the GH release). As said, having an image with a specific version tag (e.g. 2.0.1) available is not a release of sd-factory in version 2.0.1 (to stay with the example).

If you want to create a release other than for the helm chart, either implement a workflow for releasing, or ping a committer and ask to create a release manually.

**Comment by adkumar1** [comment]
Yes, you can delete the image with tag 2.0.2

What i am suppose to do in ChangeLog ?
Should i release appVersion & version 2.0.2  . Will it be fine?

**Comment by adkumar1** [comment]
Updated with latest version and changes. Please approve

**Pull request merged**
