### PR TITLE
keycloak manager fix for tests; update DEPENDENCIES

### PR DESCRIPTION
**Pull request by dvasunin**
if any of keycloak parameter is missed for a feign service it results in an exeption when token is requested. This fix disables retrieving the token if any parameter is missed.
DEPENDENCIES file is updated. No restrictions are found in the libraries

### CODE REVIEW

**Comment by dvasunin** [comment]
@Wulghash @amoldashwant please review

**Comment by amoldashwant** [comment]
Changes look good to me. All parameters are checked before making the request.

**Comment by Wulghash** [comment]
All changes seems fine from my side.

**Comment by dvasunin** [comment]
@almadigabor , please merge

**Review by almadigabor — APPROVED** [review]
LGTM

**Pull request merged**
