### PR TITLE
Unification of all supported Trust Framework versions under a single service

### PR DESCRIPTION
**Pull request by dvasunin**
With this PR APIs for all supported versions of Trust Framework (TF) are made available under single service. Namely:
- /api/1.0.6/selfdescription - for pre-22.04 TF, the first version also known as 1.0.6. Aligned with Portal Team
- /api/22.04/selfdescription - for 22.04 TF
- /api/22.10/selfdescription - for 22.10 TF

### CODE REVIEW

**Comment by dvasunin** [comment]
@carslen @Siegfriedk , can you please merge this PR?

**Comment by Siegfriedk** [comment]
@dvasunin you are downgrading the helm chart version. Is that by misstake?

Are you also aware that something like this might be broken as you should not reference github src like this? schema2210Url: https://github.com/catenax-ng/tx-sd-factory/raw/all-versions/src/main/resources/verifiablecredentials.jsonld/sd-document-v22.10.jsonld

**Comment by dvasunin** [comment]
For Helm chart version I expect a comment from our devops, Aditya. For the JSON-LD vocabulary we need a media to refer to, e.g. the one you have mentioned. We need a publicly accessable space for these documents where they can be fetched from. As we have more than one repository, I decided to keep 'old' location, on further PR we can change it to TractusX location. If we do it from the beginning then the reference will be pointed to nowhere until merging.

**Comment by Siegfriedk** [comment]
@dvasunin shouldn't that json-ld be part of some official deployment? Please revisit the architecture of this document and yes definitly move this to eclipse-tractusx if you really really really don't have any other way of exposing it

**Comment by dvasunin** [comment]
The URLs of the semantic vocabularies shall be something stable, more stable than a deployment. And all deployments shall refer to the same vocabulary independently from environment. Technically we can have them deployment specific, but in my view it is not proper way: the service can go down, migrate, but the documents created with this vocabulary may stay. I do not see better place for them than GitHub itself as we need a 'stable' media. We can also have them deployed somewhere on official CatenaX page. But we do not have direct access to that page and the documents are updated sometimes. This is why we use GitHub as a media. We do not have any better option

**Comment by Siegfriedk** [comment]
@dvasunin why would be a semantic vocabulary be more stable than a deployment? Or a release? Shouldn't it be enough to just release it with the version?

IF this is more a spec, than you need to talk to @danielmiehle or someone else (architects etc.) on were/how to release a spec.

**Comment by Siegfriedk** [comment]
@dvasunin i'm fine with merging this PR after feedback regarding the helm chart, IF this topic continues to be driven.

**Comment by adkumar1** [comment]
For helm chart version we have upgraded the version no. to 1.0.8
earlier it was 1.0.7

**Review by Siegfriedk — APPROVED** [review]

**Pull request merged**
